ktor {
    deployment {
        host = "0.0.0.0"
        port = 8080
    }
    application {
        modules = [ com.instagallery.ApplicationKt.module ]
    }
}

jwt {
    secret = "my-super-secret-key-for-instagallery-app-which-is-at-least-32-bytes"
    secret = ${?JWT_SECRET}
    issuer = "http://localhost:8080/"
    audience = "http://localhost:8080/api/v1"
    realm = "InstaGallery"
}

database {
    url = "jdbc:mysql://localhost:3306/instagallery?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
    url = ${?DB_URL}
    
    user = "root"
    user = ${?DB_USER}
    
    password = "123456789"
    password = ${?DB_PASSWORD}
}

google {
    webClientId = "647969867224-uejjvk9at6lglv6rcfvdocukkk0bqpq9.apps.googleusercontent.com"
    webClientId = ${?GOOGLE_WEB_CLIENT_ID}
}

auth {
    exposeDebugResetToken = false
    exposeDebugResetToken = ${?EXPOSE_DEBUG_RESET_TOKEN}
}

firebase {
    serviceAccountPath = ${?FIREBASE_SERVICE_ACCOUNT_PATH}
}
